name: Fetch Appstore Info 

on:
 schedule:
     - cron: "0/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - run: gem install bundler:2.1.4
      - run: bundle install
      - run: npm install 
      - run: node Sources/check_status.js
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          KEY_ID: ${{ secrets.KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          LANGUAGE: "en"
      - name: push
        uses: github-actions-x/commit@v2.7
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          github-token: ${{ secrets.TOKEN }}
          push-branch: 'master'
          commit-message: 'Store Appstore Info'
          force-add: 'true'
          files: store.db
          name: sweeepty
          email: sy.lee@iconloop.com
